#!/usr/bin/env python3
"""
=============================================================================
GPUMDkit: A User-Friendly Toolkit for GPUMD and NEP
Repository: https://github.com/zhyan0603/GPUMDkit
Citation: Z. Yan et al., GPUMDkit: A User-Friendly Toolkit for GPUMD and NEP,
          MGE Advances, 2026, 4, e70074 (https://doi.org/10.1002/mgea.70074)
=============================================================================
Script:     plt_xrd.py
Category:   Plot Scripts
Purpose:    Plot X-ray diffraction data from an XRD calculator output file.
            The second numeric column is used as the angle and the fourth
            numeric column is used as the intensity.
Usage:      gpumdkit.sh -plt xrd [xrd_file] [save]
            python plt_xrd.py [xrd_file] [save]
Arguments:
  xrd_file  XRD output file; defaults to 'xrd.out'
  save      Save the plot as 'xrd.png' instead of displaying it
Output:
  xrd.png   XRD plot (saved or displayed)
Author:     Zihan YAN (yanzihan@westlake.edu.cn)
Last-modified: 2026-08-01
=============================================================================
"""

from __future__ import annotations

import sys
from pathlib import Path


def _print_help() -> None:
    """Print the command-line usage without importing plotting packages."""
    print(" Usage: gpumdkit.sh -plt xrd [xrd_file] [save]")
    print("        python plt_xrd.py [xrd_file] [save]")
    print("")
    print(" xrd_file  XRD output file; defaults to 'xrd.out'")
    print(" save      Save the plot as 'xrd.png' instead of displaying it")
    print("")
    print(" Data columns: column 2 is the angle and column 4 is the intensity.")
    print(" Input must use the output format generated by calculator 413.")


def _parse_arguments() -> tuple[Path, bool] | None:
    """Parse the small, positional interface used by GPUMDkit plot scripts."""
    arguments = sys.argv[1:]
    if arguments and arguments[0] in {"-h", "--help"}:
        _print_help()
        return None

    if len(arguments) > 2:
        raise ValueError("expected at most an XRD file and the optional 'save'")

    save = False
    if arguments and arguments[-1] == "save":
        save = True
        arguments = arguments[:-1]

    if arguments and arguments[0] == "save":
        raise ValueError("'save' must be the last argument")

    input_file = Path(arguments[0]) if arguments else Path("xrd.out")
    return input_file, save


def _format_error(detail: str) -> ValueError:
    """Build a consistent error for files not produced by calculator 413."""
    return ValueError(
        f"{detail}. Please generate the XRD file with calculator 413 "
        "(gpumdkit.sh -> 4 -> 413)."
    )


def _validate_calculator_413_format(input_file: Path) -> list[str]:
    """Validate the header and four-column layout written by calculator 413."""
    try:
        lines = input_file.read_text(encoding="utf-8").splitlines()
    except UnicodeError as error:
        raise _format_error("XRD output is not a readable text file") from error

    comment_lines = [
        line.lstrip()[1:].strip()
        for line in lines
        if line.lstrip().startswith("#")
    ]
    has_calculator_header = (
        "Histogrammed data for standalone LAMMPS-compatible XRD" in comment_lines
        and any(line.startswith("Frames ") for line in comment_lines)
        and any(line.startswith("Elements ") for line in comment_lines)
        and any(
            line.startswith("wavelength ")
            and " 2theta " in line
            and " LP " in line
            for line in comment_lines
        )
        and "Bin Coord Count Count/Total" in comment_lines
    )
    if not has_calculator_header:
        raise _format_error("unrecognized XRD output header")

    data_lines = []
    for line_number, line in enumerate(lines, start=1):
        stripped = line.strip()
        if not stripped or line.lstrip().startswith("#"):
            continue
        fields = stripped.split()
        if len(fields) != 4:
            raise _format_error(
                f"XRD data line {line_number} must contain exactly four columns"
            )
        data_lines.append(stripped)

    if not data_lines:
        raise _format_error("XRD output contains no data rows")
    return data_lines


def _read_xrd_data(input_file: Path):
    """Read angle and intensity from columns 2 and 4 of an XRD output file."""
    import numpy as np

    if not input_file.is_file():
        raise OSError(f"XRD input file not found: {input_file}")

    _validate_calculator_413_format(input_file)
    try:
        data = np.loadtxt(input_file, comments="#", ndmin=2)
    except ValueError as error:
        raise _format_error("XRD data rows must contain numeric values") from error

    if data.ndim != 2 or data.shape[0] == 0 or data.shape[1] != 4:
        raise _format_error(
            "XRD data must contain exactly four numeric columns "
            "(angle in column 2 and intensity in column 4)"
        )

    angle = data[:, 1]
    intensity = data[:, 3]
    if not np.all(np.isfinite(angle)) or not np.all(np.isfinite(intensity)):
        raise _format_error("XRD angle and intensity columns must be finite")

    return angle, intensity


def _plot_xrd(angle, intensity, save: bool) -> None:
    """Display the XRD curve or save it for a non-interactive workflow."""
    import matplotlib.pyplot as plt
    from matplotlib import get_backend

    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "DejaVu Sans", "Liberation Sans"],
    })

    plt.figure(figsize=(5.0, 2.5), dpi=150)
    plt.plot(angle, intensity, color="C0", linewidth=1)
    plt.xlabel(r"$2\theta$ (degree)")
    plt.ylabel("Intensity")
    plt.tight_layout()

    backend = get_backend().lower()
    if save or backend in {"agg", "cairo", "pdf", "ps", "svg"}:
        plt.savefig("xrd.png", dpi=300)
        print(" Saved XRD plot to 'xrd.png'.")
    else:
        plt.show()


def main() -> int:
    """Run the XRD plotting command."""
    try:
        parsed = _parse_arguments()
        if parsed is None:
            return 0
        input_file, save = parsed
        angle, intensity = _read_xrd_data(input_file)
        _plot_xrd(angle, intensity, save)
    except (OSError, ValueError) as error:
        print(f" Error: {error}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
