#--------------------- function 6 plot & visualization ----------------------
# This module shows all available plotting tools and how to invoke them.
# Plots are called via the command-line interface: gpumdkit.sh -plt <type>
# No direct invocation is provided here to keep the interactive framework simple.

function f6_plots(){
echo " +------------------------------------------------------+"
echo " |             PLOT & VISUALIZATION TOOLS               |"
echo " +------------------------------------------------------+"
echo " |  Invoke any plot with:                               |"
echo " |    gpumdkit.sh -plt <type>                           |"
echo " |  For usage details:                                  |"
echo " |    gpumdkit.sh -plt <type> -h                        |"
echo " +------------------------------------------------------+"
echo " |  ---- MD & Structural Analysis -------------------- |"
echo " |  thermo       Plot thermostat info (T, P, E ...)     |"
echo " |  rdf          Plot radial distribution function      |"
echo " |  rdf_pmf      Plot potential of mean force (PMF)     |"
echo " |  vac          Plot velocity autocorrelation          |"
echo " |  cohesive     Plot cohesive energy curve             |"
echo " |  net_force    Plot net force distribution            |"
echo " |  plane-grid   Plot displacement plane grid           |"
echo " +------------------------------------------------------+"
echo " |  ---- Diffusion & Transport ----------------------- |"
echo " |  msd          Plot mean square displacement          |"
echo " |  msd_conv     Plot MSD convergence                   |"
echo " |  msd_all      Plot MSD for all species               |"
echo " |  sdc          Plot self diffusion coefficient        |"
echo " |  msd_sdc      Plot MSD and SDC together              |"
echo " |  sigma        Plot Arrhenius ionic conductivity      |"
echo " |  D            Plot Arrhenius diffusivity             |"
echo " |  sigma_xyz    Plot directional Arrhenius sigma       |"
echo " |  D_xyz        Plot directional Arrhenius D           |"
echo " +------------------------------------------------------+"
echo " |  ---- Heat Transport ------------------------------ |"
echo " |  emd          Plot EMD results                       |"
echo " |  nemd         Plot NEMD results                      |"
echo " |  hnemd        Plot HNEMD results                     |"
echo " |  viscosity    Plot viscosity                         |"
echo " +------------------------------------------------------+"
echo " |  ---- Phonons & Electronic ----------------------- |"
echo " |  pdos         Plot VAC and PDOS                      |"
echo " |  doas         Plot density of atomistic states       |"
echo " |  born_charge  Plot Born effective charges            |"
echo " +------------------------------------------------------+"
echo " |  ---- NEP Training & Evaluation ------------------ |"
echo " |  train        Plot NEP training results              |"
echo " |  prediction   Plot NEP prediction results            |"
echo " |  train_test   Plot NEP train and test results        |"
echo " |  restart      Plot parameters in nep.restart         |"
echo " |  dimer        Plot dimer energy/force curve          |"
echo " |  force_errors Plot force errors                      |"
echo " |  des          Plot descriptors                       |"
echo " |  charge       Plot charge distribution               |"
echo " |  lr           Plot learning rate                     |"
echo " |  parity_density Plot parity plot density            |"
echo " +------------------------------------------------------+"
}
