function f6_plots_one_column(){
    echo " +---------------------------------------------------------+"
    echo " |                PLOT & VISUALIZATION TOOLS               |"
    echo " +---------------------------------------------------------+"
    echo " |  Usage: gpumdkit.sh -plt <type>                         |"
    echo " +---------------------------------------------------------+"
    echo " |                NEP Training & Evaluation                |"
    echo " +---------------------------------------------------------+"
    echo " |  train          Plot NEP training results               |"
    echo " |  prediction     Plot NEP prediction results             |"
    echo " |  train_test     Plot NEP train and test results         |"
    echo " |  parity_density Plot parity density plot                |"
    echo " |  train_density  Plot training results in density plot   |" 
    echo " |  restart        Plot parameters in nep.restart          |"
    echo " |  charge         Plot charge distribution                |"
    echo " |  born_charge    Plot Born effective charges             |"    
    echo " |  dimer          Plot dimer energy/force curve           |"
    echo " |  force_errors   Plot force errors                       |"
    echo " |  des            Plot descriptors                        |"       
    echo " |  lr             Plot learning rate for gnep             |"
    echo " +---------------------------------------------------------+"
    echo " |                 Diffusion & Transport                   |"
    echo " +---------------------------------------------------------+"
    echo " |  msd            Plot mean square displacement (MSD)     |"
    echo " |  msd_conv       Plot MSD convergence                    |"
    echo " |  msd_all        Plot MSD for all species                |"
    echo " |  sdc            Plot self diffusion coefficient         |"
    echo " |  msd_sdc        Plot MSD and SDC together               |"
    echo " |  sigma          Plot Arrhenius ionic conductivity       |"
    echo " |  D              Plot Arrhenius diffusivity              |"
    echo " |  sigma_xyz      Plot directional Arrhenius sigma        |"
    echo " |  D_xyz          Plot directional Arrhenius D            |"
    echo " |  doas           Plot density of atomistic states        |"
    echo " +---------------------------------------------------------+"
    echo " |                 MD & Structural Analysis                |"
    echo " +---------------------------------------------------------+"
    echo " |  thermo         Plot thermo info in thermo.out          |"
    echo " |  thermo2/3      Plot thermo in different styles         |"    
    echo " |  rdf            Plot radial distribution function       |"
    echo " |  rdf_pmf        Plot potential of mean force            |"
    echo " |  vac            Plot velocity autocorrelation           |"
    echo " |  cohesive       Plot cohesive energy curve              |"
    echo " |  net_force      Plot net force distribution             |"
    echo " |  plane-grid     Plot displacement plane grid            |"
    echo " +---------------------------------------------------------+"
    echo " |                     Heat Transport                      |"
    echo " +---------------------------------------------------------+"
    echo " |  emd            Plot EMD results                        |"
    echo " |  nemd           Plot NEMD results                       |"
    echo " |  hnemd          Plot HNEMD results                      |"
    echo " |  viscosity      Plot viscosity                          |"
    echo " +---------------------------------------------------------+"
    echo " |                         Phonons                         |"
    echo " +---------------------------------------------------------+"
    echo " |  pdos           Plot VAC and PDOS                       |"
    echo " +---------------------------------------------------------+"
    # echo " |                   Miscellaneous Tools                   |"
    # echo " +---------------------------------------------------------+"
    # echo " |  Developing ...                                         |"
    # echo " +---------------------------------------------------------+"
}

function f6_plots_two_column(){
    echo " +-----------------------------------------------------------------------------------------------+"
    echo " |                     GPUMDkit ${VERSION} PLOT & VISUALIZATION TOOLS              |"
    echo " +-----------------------------------------------------------------------------------------------+"
    echo " |  Usage: gpumdkit.sh -plt <type>                        Help: gpumdkit.sh -plt <type> -h       |"
    echo " +-----------------------------------------------------------------------------------------------+"
    echo " |                                    NEP Training & Evaluation                                  |"
    echo " +-----------------------------------------------------------------------------------------------+"
    echo " |  train          - NEP training results           prediction     - NEP prediction results      |"
    echo " |  train_test     - NEP train and test results     parity_density - Parity density plot         |"
    echo " |  train_density  - Training results density plot  restart        - Parameters in nep.restart   |"
    echo " |  charge         - Charge distribution            born_charge    - Born effective charges      |"
    echo " |  dimer          - Dimer energy/force curve       force_errors   - Force errors                |"
    echo " |  des            - Descriptors                    lr             - Learning rate for gnep      |"
    echo " +-----------------------------------------------------------------------------------------------+"
    echo " |                                     Diffusion & Transport                                     |"
    echo " +-----------------------------------------------------------------------------------------------+"
    echo " |  msd            - Mean square displacement       msd_conv       - MSD convergence             |"
    echo " |  msd_all        - MSD for all species            sdc            - Self diffusion coefficient  |"
    echo " |  msd_sdc        - MSD and SDC together           sigma          - Arrhenius ionic conductivity|"
    echo " |  D              - Arrhenius diffusivity          sigma_xyz      - Directional Arrhenius sigma |"
    echo " |  D_xyz          - Directional Arrhenius D                                                     |"
    echo " +-----------------------------------------------------------------------------------------------+"
    echo " |                                    MD & Structural Analysis                                   |"
    echo " +-----------------------------------------------------------------------------------------------+"
    echo " |  thermo         - thermo info in thermo.out      thermo2/3      - Thermo in different styles  |"
    echo " |  rdf            - Radial distribution function   rdf_pmf        - Potential of mean force     |"
    echo " |  vac            - Velocity autocorrelation       cohesive       - Cohesive energy curve       |"
    echo " |  net_force      - Net force distribution         plane-grid     - Displacement plane grid     |"
    echo " |  doas           - Density of atomistic states                                                 |"
    echo " +-----------------------------------------------------------------------------------------------+"
    echo " |                                        Heat Transport                                         |"
    echo " +-----------------------------------------------------------------------------------------------+"
    echo " |  emd            - EMD results                    nemd           - NEMD results                |"
    echo " |  hnemd          - HNEMD results                  viscosity      - Viscosity                   |"
    echo " +-----------------------------------------------------------------------------------------------+"
    echo " |                                          Phonons                                              |"
    echo " +-----------------------------------------------------------------------------------------------+"
    echo " |  pdos           - VAC and PDOS                                                                |"
    echo " +-----------------------------------------------------------------------------------------------+"
    # echo " |                                       Miscellaneous Tools                                     |"
    # echo " +-----------------------------------------------------------------------------------------------+"
    # echo " |  Developing ...                                                                               |"
    # echo " +-----------------------------------------------------------------------------------------------+"
}
